# Generated by Django 2.2.6 on 2021-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210428_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('pk',), 'verbose_name': 'Подборка записей', 'verbose_name_plural': 'Подборки записей'},
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Краткое описание принципов объединения записей в подборку, тематика и основные правила поведения', verbose_name='Описание подборки'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Укажите адрес для страницы подборки. Используйте только латиницу, цифры, дефисы и знаки подчёркивания', unique=True, verbose_name='Часть адресной строки для подборки'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Группа, сообщество, подборка записей, суть одна, в этом месте собраны сообщения, имеющие некую общность. Название подборки призвано её отражать', max_length=200, unique=True, verbose_name='Название подборки'),
        ),
    ]
