# Generated by Django 2.2.6 on 2021-06-17 14:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20210617_1709'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='not_yourself_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='not_yourself_follow'),
        ),
    ]
